# Generated by Django 6.1.1 on 2026-09-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(default='Sin especificar', max_length=100),
            preserve_default=False,
        ),
    ]
