# Generated by Django 6.1.1 on 2026-10-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_perfilorganizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilorganizador',
            name='limite_horas_diarias',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
